"""new field

Revision ID: a0075cc71d70
Revises: 9d70f2145bb3
Create Date: 2023-02-19 15:59:08.762488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0075cc71d70'
down_revision = '9d70f2145bb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error')
    # ### end Alembic commands ###
